language: node_js
sudo: false
node_js:
  - '6'
install:
  - npm install
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x deploy.sh && ./deploy.sh
  on:
    all_branches: true
notifications:
  email: false
